### ISSUE TITLE
V2 version idea: ESP32 with A4988

### ISSUE THREAD

**Issue by Oxmaster** [Dave19171/split-flap#1]
ESP32 has more than 21 GPIO pins needed for 10 flaps version, so with single MCU you could do all the work. Unless I am missing something.

Tie A4988 DIR pin to make it only spin in one way.

2 pins per flap: STEP and hall sensor output.
1 pin for ENA on all A4988 drivers.

Additionally: add 12V LED strip support to illuminate the flaps and LDR to auto change the brightness.

**Comment by Dave19171** [comment]
Feel free to make a version 2.
A version with fewer microcontrollers would certainly be a bit cheaper and less power-hungry, but not with A4988. I saw prices from $4 to $7 per piece.
My idea would be to use the ULN2003 with shift registers if that's possible. But the code would have to be written almost from scratch.
