### ISSUE TITLE
Unit Frame Assembly Missing Holes for M3 nuts

### ISSUE THREAD

**Issue by ThomDyson** [Dave19171/split-flap#2]
First, thank you so much for this project. I've had to learn Arduino and how to order custom PCBs, so this great.

In the instructions, section 5.2.2 says "Push two M3 nuts diagonally in the back of the frame. Use a screw to pull the nut if necessary."

I think this is to mount the stepper motor, but there are no holes in the unit frame for the M3 nuts under the stepper motor.

**Comment by Dave19171** [comment]
This is not to mount the stepper motor, you need M4 screws for that. These are for attaching the frame to the HousingFrame
![M3 Nut Holes](https://user-images.githubusercontent.com/28829507/125613943-85256792-89d9-47c6-83c3-be6e9fef5406.png)

**Comment by ThomDyson** [comment]
Got it. Thanks.
