### ISSUE TITLE
f3d file, 

### ISSUE THREAD

**Issue by chaos-dotcom** [Dave19171/split-flap#24]
Hi David, 
Thanks so much for all your hard work, if you wouldnt mind I'm trying to create a 60 flap version and was wondering if you could provide the parametric fusion file so I could make these edits more easily than I am now! 

With Pride
J

**Comment by ivanseidel** [comment]
Hi @davidkingsman i was looking for the same thing. Is the .f3d file available somewhere?

**Comment by davidkingsman** [comment]
> Hi [@davidkingsman](https://github.com/davidkingsman) i was looking for the same thing. Is the .f3d file available somewhere?

There you go: http://seafile.david-koenigsmann.com/f/9001a4d1bdee4e9d8369/ (expires in 3 days)
