### ISSUE TITLE
Can't get ESP Master to communicate with flaps

### ISSUE THREAD

**Issue by Azer0s** [Dave19171/split-flap#25]
The flaps all home, SDA and SCL have continuity from flap 0 to flap 9 but I can't get them to communicate. I tried using a programmer for the ESP01 with pinouts and connected TX, RX and GND. I got this error message: 
```
0:-1
Try to wake up unit
A unit in the display is sleeping
Waiting for display to stop
```
Do you maybe have an idea?
Fyi I have R1-R4, Q1-Q2. C5 and U9 on all PCBs. Can that cause the issue? It shouldn't cause it is just power delivery, right?

**Comment by Azer0s** [comment]
Nvm I had the ESP01 in serial debug mode

**Comment by stoneWeb** [comment]
How did you solve this problem? It seems I'm experiencing the same issue as you. It was working fine initially, but then I'm not sure what I did, and now it's not working anymore. The serial output is also like this:
```
0:-1
Try to wake up unit
A unit in the display is sleeping
Waiting for display to stop
```
